[package]
name = "serde_yaml_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "*"
serde = { version = "*", features = ["derive"] }
strum = "*"
