[package]
name = "ssh-client-session"
version = "0.1.0"
authors = ["micki <github@com-science.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9"
tokio = { version = "*", features = ["full"] }
