[package]
name = "barycenter-concurrent"
version = "0.1.0"
authors = ["micki <github@com-science.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7"
rayon = "1"
